language: python
python:
  - "2.7"
#  - "3.5"

# command to install dependencies
install:
  - pip install -U pytest
  - pip install flake8
  - pip install .

# command to run tests
script:
  - flake8
  - pytest -v
