name: checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.7', '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: setup python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: install deps
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        pip install .
    - name: lint
      run: |
        flake8
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.7', '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: setup python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: install deps
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt
        pip install .
    - name: pytest
      run: |
        pytest -v
